### ISSUE TITLE
building gitg gives "/lib/ld-linux-x86-64.so.2: bad ELF interpreter: No such file or directory"

### ISSUE THREAD

**Issue by vrutkovs** [alexlarsson/xdg-app#119]
Building gitg from https://gist.github.com/vrutkovs/67e6189ee4ee1f091ad06d375834dcf9 using scripts from https://github.com/alexlarsson/gnome-apps-nightly:
```
...
Removing files/include/git2/attr.h
Removing files/include/git2/annotated_commit.h
Removing files/include/git2.h
Removing files/include/git2
Removing files/include/gee-0.8/gee.h
Removing files/include/gee-0.8
Removing files/include
Removing files/bin/peas-demo
error: Error opening file: No such file or directory
$ ./app/files/bin/gitg
bash: ./app/files/bin/gitg: /lib/ld-linux-x86-64.so.2: bad ELF interpreter: No such file or directory
$ ldd  ./app/files/bin/gitg
 ...
libgit2.so.24 => not found
...
```

**Comment by alexlarsson** [comment]
Did you attach the wrong file to the gist? That one is just gnome-builder...

**Comment by vrutkovs** [comment]
Oops, sorry, updated the gist

**Comment by alexlarsson** [comment]
I added a better error message to master:

error: Can't load desktop file org.gnome.Gitg.desktop: Error opening file: No such file or directory

You need to rename the desktop file. You can do that by adding:

     "rename-desktop-file": "gitg.desktop",

**Comment by alexlarsson** [comment]
Anyway, if you want to test the app you can't just run it directly
You can do this however:
```
xdg-app-builder --run app org.gnome.Gitg.json gitg
```

**Comment by vrutkovs** [comment]
Right, that worked, thanks!
