### ISSUE TITLE
Allow exposing optical media devices

### ISSUE THREAD

**Issue by hadess** [alexlarsson/xdg-app#139]
For DVD and VCD playback to work in totem, the application might need access to the device itself, as well as the mount point for that filesystem (to check what is on the disc).

**Comment by alexlarsson** [comment]
I understand the need, but direct block device access is scary stuff it things go wrong. I mean, a cdrom device is just a block device node like any other, such as your ide disks...

How does user permissions for dvd devices work? What makes it possible for the user to read the dvd drive device?

**Comment by hadess** [comment]
Right now? systemd-udev has rules to mark "CD drives" (meaning any optical media) as such:
/usr/lib/udev/rules.d/50-udev-default.rules
and
/usr/lib/udev/rules.d/60-cdrom_id.rules

I don't what changes the permissions to access it though.

**Comment by alexlarsson** [comment]
This issue was moved to flatpak/flatpak#12
