### ISSUE TITLE
xdg-app errors during completion

### ISSUE THREAD

**Issue by hadess** [alexlarsson/xdg-app#141]
When tabbing through for completion, a number of errors can occur:
```
$ xdg-app install <tab><tab>error: Error creating directory: Permission denied
--user
```

With `local` being a local repository:
```
$ xdg-app install --user local <tab><tab>error: Invalid 'file' URI: file://home/hadess/Projects/jhbuild/gnome-apps-nightly/repo/summary.sig
```

**Comment by alexlarsson** [comment]
The tab completion is a separate shell script which is not really up-to-date. I want to handle it in the C code in gdbus-style...

**Comment by alexlarsson** [comment]
This issue was moved to flatpak/flatpak#11
