### ISSUE TITLE
Bad error message with no locale data

### ISSUE THREAD

**Issue by hadess** [alexlarsson/xdg-app#145]
Builds fail when there's no locale data:
```
exporting hu.mplayerhq.app.Locale to repo
error: Build directory app not initialized
Export failed: Child process exited with code 1
```

A better error message would mention adding `"separate-locales": false` to the json file.

**Comment by alexlarsson** [comment]
This is fixed in git master i believe:
https://cgit.freedesktop.org/xdg-app/xdg-app/commit/?id=39279c8b8bc2bb946473724a0cb8dd131f489a61
