### ISSUE TITLE
Doesn't download file types

### ISSUE THREAD

**Issue by hadess** [alexlarsson/xdg-app#146]
For example, the stand-alone waf file here I would expect to be downloaded as the filename mentioned for building.

```
                {   
                    "type": "file",
                    "url": "https://waf.io/waf-1.8.12",
                    "sha256": "01bf2beab2106d1558800c8709bc2c8e496d3da4a2ca343fe091f22fca60c98b",
                    "dest-filename": "waf"
                },  
```

**Comment by hadess** [comment]
Note that I just realised that we'd be missing a way to set the executable bit on the downloaded file.

**Comment by alexlarsson** [comment]
This issue was moved to flatpak/flatpak#8
