### ISSUE TITLE
xdg-app-builder: Specify git commit to use

### ISSUE THREAD

**Issue by hbons** [alexlarsson/xdg-app#148]
This would be more secure (equivalent to specifying a sha256 for archives) and convenient (rebuilds won't be needed on every new commit).

**Comment by alexlarsson** [comment]
Use "branch" it supports both branch names and commit IDs

**Comment by hbons** [comment]
Can these be separate options? People don't read, this is more obvious when reading json files as examples and makes the spec more readable. :)

**Comment by alexlarsson** [comment]
Its just the string that is passed to the "git checkout $branch" command, which supports commit ids as well as branch or tag names. I don't think adding a separate property for it makes a lot of sense.
