### ISSUE TITLE
contains GTester leftovers

### ISSUE THREAD

**Issue by smcv** [alexlarsson/xdg-app#150]
xdg-app 0.5.2 tries to run its build-time tests under both Automake (`TESTS`) and GTester (`TEST_PROGS`). In Debian I apply [a patch](https://anonscm.debian.org/git/collab-maint/xdg-app.git/tree/debian/patches/Don-t-run-tests-under-gtester-in-addition-to-make-check.patch) to disable the GTester part, because there's no point in having both, and GTester doesn't/didn't support treating a test that exits 77 as "every test-case was skipped".

GTester is [somewhat deprecated, according to ebassi](https://bugzilla.gnome.org/show_bug.cgi?id=692125#c42).

I haven't tried it yet, but it looks as though git master has fully migrated from GTester to `glib-tap.mk` (like GLib did a while ago), which means that `Makefile.gtester` and all references to `TEST_PROGS` can hopefully be removed.

**Comment by smcv** [comment]
> doesn't/didn't support treating a test that exits 77 as "every test-case was skipped"

This happens on Debian's official autobuilders, which disable kernel module loading as a security hardening measure, preventing FUSE from being tested at build-time. We'll hopefully be able to test the FUSE bits with installed-tests, which run on different infrastructure.

**Comment by alexlarsson** [comment]
I'm not in any way an expert on test setups, but I believe the GTester stuff has been properly exorcised in master, and we now have installed tests, as well as actual tests you know, testing stuff..

**Comment by smcv** [comment]
> I believe the GTester stuff has been properly exorcised in master

Looks good to me!
