### ISSUE TITLE
Investigate libva/VDPAU support

### ISSUE THREAD

**Issue by hadess** [alexlarsson/xdg-app#158]
Similar to the joystick, or optical drives support, we'll need to investigate libva/VDPAU support.

**Comment by gcampax** [comment]
Shouldn't be handled like GL?
As far opening the device, you only need /dev/dri, which you have.

By the way, the intel libva driver is not built, but the vdpau-to-libva adapters (from mesa) are built, and so are the gallium vdpau drivers. Which means it should "just work" on radeon/nvidia with the free drivers.

**Comment by alexlarsson** [comment]
I don't really know how vdpau stuff works, but i *think* I added the right modules for this to the fd.o runtimes, and with dri access this should "just work". But, i've never tested it.

Didn't know we were missing an intel driver. We should add that then.

**Comment by hadess** [comment]
Then we'd likely need an extension point for that, as the Intel libva driver apparently contains patent encumbered code.

**Comment by alexlarsson** [comment]
ah...

**Comment by alexlarsson** [comment]
This issue was moved to flatpak/flatpak#4
