### ISSUE TITLE
avoid accessing files as uid 0/with CAP_DAC_OVERRIDE

### ISSUE THREAD

**Issue by cgwalters** [alexlarsson/xdg-app#47]
See:
https://git.gnome.org/browse/linux-user-chroot/commit/?id=c4388a624de392a72a5826b0d61c2aa21f283ede
https://git.gnome.org/browse/linux-user-chroot/commit/?id=04028db1d9f7909f4c86d9b4d4a8640e65fd11f1

**Comment by alexlarsson** [comment]
I fixed this with https://github.com/alexlarsson/xdg-app/commit/b2ec77fb2fe583a96a2006645e726cd2fe640bd3 by not running the helper as root but instead as the real user, but with some extra caps. I will also do a second pass that optionally uses file-caps instead of setuid.
