### ISSUE TITLE
Use resolv.conf from host machine

### ISSUE THREAD

**Issue by vrutkovs** [alexlarsson/xdg-app#59]
Currently any operation involving dns will fail:
```
$ jhbuild run xdg-app run --devel --command=bash org.gnome.GEdit                                                                                                                                        
bash-4.3$ cat /etc/resolv.conf
cat: /etc/resolv.conf: No such file or directory
```
This breaks some gnome apps e.g. Dictionary

**Comment by alexlarsson** [comment]
This is a build/install issue on your side. xdg-app contains a dbus service (xdg-app-session.service) which if installed is started by xdg-app when it starts an app. This service maintains an up-to-date copy of resolv.conf in a /run/user/1000/xdg-app-monitor/ which is used by the xdg-app runtime via a symlink.

You need to ensure that your session dbus daemon finds the service file, or manually start the helper.
