### ISSUE TITLE
xdg-app run quits with "can't bind monitor dir"

### ISSUE THREAD

**Issue by porst17** [alexlarsson/xdg-app#78]
I successfully compiled and installed `xdg-app` 0.3.2 under Ubuntu 14.04 and installed the `org.freedesktop.Platform` runtime as well as `org.freedesktop.glxgears` from your repositories. However, when I
```
xdg-app -v run org.freedesktop.glxgears
```
it quits with
```
XA: Allowing ipc access
XA: Allowing dri access
XA: Allowing x11 access
XA: Allowing wayland access
can't bind monitor dir
```
Same for `org.gnome.Platform` together with `org.gnome.gedit`:
```
XA: Allowing ipc access
XA: Allowing network access
XA: Allowing host-fs access
XA: Allowing x11 access
XA: Allowing wayland access
XA: Allowing session-dbus access
can't bind monitor dir
``` 
Is this a bug or am I missing something?

**Comment by alexlarsson** [comment]
Not sure exactly what is causing this. xdg-app contains a dbus activated helper (/usr/libexec/xdg-app-session-helper) that "xdg-app run" starts. This manages a directory, which for me is /run/user/1000/xdg-app-monitor/ and this is mounted into the container. (It countains some config files that we want to propagate changes to from the host system to the container, like resolv.conf and timezone info).

For some reason in your case the helper is returning a path for the monitor and then we fail to mount that path in the container.

Can you try running the xdg-app run command under strace -f, so we can see how the bind syscall fails.

**Comment by alexlarsson** [comment]
You should be able to see the local directory it uses for you with:

gdbus call --session --dest org.freedesktop.XdgApp.SessionHelper --object-path /org/freedesktop/XdgApp/SessionHelper --method org.freedesktop.XdgApp.SessionHelper.RequestMonitor

**Comment by porst17** [comment]
```
$ gdbus call --session --dest org.freedesktop.XdgApp.SessionHelper --object-path /org/freedesktop/XdgApp/SessionHelper --method org.freedesktop.XdgApp.SessionHelper.RequestMonitor
(b'/run/user/1000/xdg-app-monitor',)
```
I have `rwx` permissions on this path, but the bind mount fails with some `Operation not permitted` error.

```
$ strace -f xdg-app run org.gnome.gedit
.....
probably unrelated strace output 
.....
[pid  2921] mount("/run/user/1000/xdg-app-monitor", "run/user/1000/xdg-app-monitor", NULL, MS_MGC_VAL|MS_BIND, NULL) = 0
[pid  2921] mount("none", "run/user/1000/xdg-app-monitor", NULL, MS_MGC_VAL|MS_RDONLY|MS_NOSUID|MS_NODEV|MS_REMOUNT|MS_BIND, NULL) = -1 EPERM (Operation not permitted)
[pid  2921] write(2, "can't bind monitor dir", 22can't bind monitor dir) = 22
[pid  2921] write(2, "\n", 1
)           = 1
[pid  2921] exit_group(1)               = ?
[pid  2921] +++ exited with 1 +++
[pid  2920] <... poll resumed> )        = 1
[pid  2917] <... poll resumed> )        = 1 ([{fd=4, revents=POLLIN}])
[pid  2920] read(4,  <unfinished ...>
[pid  2917] read(3,  <unfinished ...>
[pid  2920] <... read resumed> 0x7ffd2ad63070, 16) = -1 EAGAIN (Resource temporarily unavailable)
[pid  2917] <... read resumed> 0x7ffe05022640, 8) = -1 EAGAIN (Resource temporarily unavailable)
[pid  2920] write(4, 0x7ffd2ad63058, 8 <unfinished ...>
[pid  2917] read(4,  <unfinished ...>
[pid  2920] <... write resumed> )       = 8
[pid  2917] <... read resumed> "\21\0\0\0\0\0\0\0\1\0\0\0i\v\0\0\350\3\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 128) = 128
[pid  2920] unlink(0x19c37e0 <unfinished ...>
[pid  2917] exit_group(1)               = ?
[pid  2920] <... unlink resumed> )      = 0
[pid  2920] write(4, 0x7ffd2ad62d68, 8 <unfinished ...>
[pid  2917] +++ exited with 1 +++
<... write resumed> )                   = 8
exit_group(0)                           = ?
+++ exited with 0 +++
```

I can post the full `strace -f` output if needed.

**Comment by alexlarsson** [comment]
So, the mount succeeds, but remounting it read-only, nosuid, nodev is getting an EPERM
What mount is /run/user/1000/xdg-app-monitor on, and what mount flags does that have?

**Comment by alexlarsson** [comment]
I have a suspicion that this is caused by the other flags. We mainly want the MS_RDONLY part, and it may be failing because the original mount does not have e.g. nosuid, but we try to add that flag.

**Comment by alexlarsson** [comment]
For the record:
cat /proc/self/mountinfo | grep /run/user/1000
169 22 0:51 / /run/user/1000 rw,nosuid,nodev,relatime shared:113 - tmpfs tmpfs rw,seclabel,size=1634248k,mode=700,uid=1000,gid=10

**Comment by porst17** [comment]
```
$ cat /proc/self/mountinfo | grep /run/user/1000
48 29 0:37 / /run/user/1000/gvfs rw,nosuid,nodev,relatime - fuse.gvfsd-fuse gvfsd-fuse rw,user_id=1000,group_id=1000
```

**Comment by alexlarsson** [comment]
Thats not the same though, that is the gvfs subdir, i guess you don't have a separate mount for /run/user/1000, but rather it uses the same mount as /run ?

**Comment by porst17** [comment]
Doesn't look like there is a separate mount for `/run/user/1000`. Maybe that's specific to Ubuntu or Debian in general. I don't know. There is a separate mount for `/run/user`, though:
```
$ cat /proc/self/mountinfo | grep /run/
27 21 0:19 / /run/lock rw,nosuid,nodev,noexec,relatime - tmpfs none rw,size=5120k
28 21 0:20 / /run/shm rw,nosuid,nodev,relatime - tmpfs none rw
29 21 0:21 / /run/user rw,nosuid,nodev,noexec,relatime - tmpfs none rw,size=102400k,mode=755
48 29 0:37 / /run/user/1000/gvfs rw,nosuid,nodev,relatime - fuse.gvfsd-fuse gvfsd-fuse rw,user_id=1000,group_id=1000
```

**Comment by alexlarsson** [comment]
Hmmm, it has noexec, which means i guess that the xdg-app remount is trying to "remove" that flag.
Just to test, can you try to manually remount your /run/user and remove the noexec flag?

**Comment by alexlarsson** [comment]
Ok, i can reproduce here by adding a noexec flag, will take a look.

**Comment by alexlarsson** [comment]
https://github.com/alexlarsson/xdg-app/commit/5da240c24f076f79b802d44d7bc2cec493a1e23f should fix this for you

**Comment by porst17** [comment]
Tested. Works for me.
