### ISSUE TITLE
Building the doc failes due to --nonet option of xsltproc

### ISSUE THREAD

**Issue by porst17** [alexlarsson/xdg-app#79]
When I call `make` in `doc`, it fails with
```
  GEN      xdg-app.1
I/O error : Attempt to load network entity http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl
warning: failed to load external entity "http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl"
cannot parse http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl
make: *** [xdg-app.1] Error 4
```
If I remove the `--nonet` from `XSLTPROC_FLAGS` in `doc/Makefile.am` and configure again, the documentation is built successfully (although it's building extremely slowly, i.e. it takes several minutes).

Not sure if this is supposed to be an optimization ... but it just didn't work for me.

**Comment by alexlarsson** [comment]
This means you need some docbook package installed that has the xsl. I don't know what it is on ubuntu, but on fedora its the docbook-style-xsl package i believe.

**Comment by porst17** [comment]
On Ubuntu, it's
```
sudo apt-get install docbook-xsl
```
Builds very quickly afterwards.

Shouldn't the existence of the xsl files be checked by the configure script somehow?

By the way: `make clean` in `doc` doesn't delete the `.1` files. I had to `rm doc/*.1` to debug this issue.

**Comment by alexlarsson** [comment]
I guess i can steal some auto* stuff for that.

**Comment by alexlarsson** [comment]
fixed in master

**Comment by porst17** [comment]
For the record: fixed in d52c09165c36a1f771d3e4db01cb18ac8fd75be6

**Comment by porst17** [comment]
The new check seems to work fine. I tested it in Ubuntu 14.04 after removing the package `docbook-xsl` and `./configure` complained about the missing XLS stylesheet. Reinstalling `docbook-xsl` made it work again.

In addition, I had to install the package `libxml2-utils`. Otherwise, `./configure` was unable to test for the style sheet via `xmlcatalog`.

Good job!

**Comment by alexlarsson** [comment]
I just stole the checks from glib :)
