### ISSUE TITLE
inkscape: error while loading shared libraries

### ISSUE THREAD

**Issue by steko** [alexlarsson/xdg-app#93]
Hello, the latest org.inkscape.InkscapeDevel app fails with the following error message:

```
$ xdg-app run org.inkscape.InkscapeDevel
inkscape: error while loading shared libraries: libgomp.so.1: cannot open shared object file: No such file or directory
```

I'm on Debian sid. The shared library is installed:

```
$ dpkg -S libgomp.so.1
libgomp1:amd64: /usr/lib/x86_64-linux-gnu/libgomp.so.1
libgomp1:amd64: /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0
```

I don't know if this is an xdg-app problem or an Inkscape problem though.

**Comment by alexlarsson** [comment]
Can you try
 
 xdg-app update-runtime --user org.gnome.Platform

I added some stuff to the runtime.

**Comment by steko** [comment]
OK, something's wrong with my install though, I'm afraid:

```sh
$ xdg-app update-runtime --user gnome org.gnome.GnomePlatform
error: 'gnome' is not a valid runtime name

$ xdg-app install-runtime --user gnome org.gnome.GnomePlatform

error: While pulling runtime/org.gnome.GnomePlatform/x86_64/master from remote gnome: No such branch 'runtime/org.gnome.GnomePlatform/x86_64/master' in repository summary
```

**Comment by alexlarsson** [comment]
oh, sorry
xdg-app update-runtime --user org.gnome.Platform 3.18

**Comment by steko** [comment]
Thanks, It works and it fixes the issue with the shared library. Should I assume that the runtime has to be updated regularly?

**Comment by alexlarsson** [comment]
Well, the long term goal is that the runtime should never change in a way that breaks apps like this, just for security fixes. However, since this is early i'm playing a bit loose with that.

That said, its always nice to update the runtimes to get security updates. Obviously the long term goal is for the updates to be an automatic background thing.
