### ISSUE TITLE
Unable to install apps

### ISSUE THREAD

**Issue by iBeliever** [alexlarsson/xdg-app#97]
I successfully installed the GNOME runtime. However, installing gedit fails:

    $ xdg-app install-app --user gnome-test-apps org.gnome.gedit

    Receiving objects: 99% (1804/1812) 47.8 kB/s 6.0 MB           
    Creating new namespace failed: Invalid argument
    Creating new namespace failed: Invalid argument
    Creating new namespace failed: Invalid argument

I'm running from the master branch on Arch Linux. I looked at the code but didn't understand it enough to figure out what was causing this error message. Do I have the wrong version of something installed?

**Comment by alexlarsson** [comment]
Arch does not have user namespaces on in the kernel. You need to build xdg-app with --disable-userns to make it use the setuid fallback.

**Comment by iBeliever** [comment]
Thanks, that worked!
